name: dl4nlp
channels:
- pytorch
- defaults
- conda-forge
dependencies:
  - python=3.7.*
  - pytorch=1.2.0
  - tensorboardX=1.8.*
  - matplotlib==3.1.1
  - numpy=1.17.*
  - tqdm=4.35.*
  - h5py=2.10.*
  - pandas=0.25.*
#  TODO: add what you need!!
